service: serverless-wsgi-demo

frameworkVersion: "3"

custom:
  wsgi:
    app: helloworld.wsgi.application

provider:
  name: aws
  runtime: python3.8

package:
  individually: false
  patterns:
    - "!**"
    - helloworld/**
    - pages/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
